### ISSUE TITLE
Solafans MPPT

### ISSUE THREAD

**Issue by woodie2** [syssi/esphome-jnge-mppt-controller#34]
Hello, is it possible to support the following MPPT? Do the communication protocol look similar?

[Translated copy of MPPT communication protocol.pdf](https://github.com/syssi/esphome-jnge-mppt-controller/files/9849922/Translated.copy.of.MPPT.communication.protocol.pdf)

https://www.alibaba.com/product-detail/Advanced-Technology-96V-45A-MPPT-Solar_1600462053979.html

**Comment by syssi** [comment]
The protocol is different but the skeleton of this component could be used to implement this inverter / protocol.

**Comment by syssi** [comment]
Did you find a solution to talk to the device? Do you own the device already?

**Comment by woodie2** [comment]
> Did you find a solution to talk to the device? Do you own the device already?

yes I have the device, and it is working with their software, but I don't have the time to implement the new protocol here.

**Comment by JasonL5** [comment]
Have you ever done the protocol yet
